nathannau_boardmanager_register:
    path: /boardmanager/register/{post}/{hash}
    defaults: { _controller: nathannau.boardmanager.main:registerAction }
    requirements:
        post: \d+
        hash: '[0-9a-f]{32}'
nathannau_boardmanager_unregister:
    path: /boardmanager/unregister/{post}/{hash}
    defaults: { _controller: nathannau.boardmanager.main:unregisterAction }
    requirements:
        post: \d+
        hash: '[0-9a-f]{32}'
nathannau_boardmanager_open:
    path: /boardmanager/open/{post}
    defaults: { _controller: nathannau.boardmanager.main:openAction }
    requirements:
        post: \d+
nathannau_boardmanager_cancel:
    path: /boardmanager/cancel/{post}/{hash}
    defaults: { _controller: nathannau.boardmanager.main:cancelAction }
    requirements:
        post: \d+
        hash: '[0-9a-f]{32}'
